# Generated by Django 3.1.7 on 2021-04-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_caracteristicas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracteristicas',
            new_name='Caracteristica',
        ),
    ]
