# Generated by Django 3.1.7 on 2021-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210402_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket'), ('lni-leaf', 'leaf'), ('lni-laptop-phone', 'laptop-phone')], max_length=16, verbose_name='Icone'),
        ),
    ]
